apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argocd-example-
spec:
  ttlStrategy:
    secondsAfterCompletion: 300
    secondsAfterFailure: 300
    secondsAfterSuccess: 300
  serviceAccountName: workflow
  entrypoint: main
  templates:
    - name: main
      plugin:
        argocd:
          serverUrl: argocd-server.argocd.svc.cluster.local
          actions:
            - sync:
                project: default
                apps:
                  - guestbook
