apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argocd-example-
spec:
  ttlStrategy:
    secondsAfterCompletion: 300
    secondsAfterFailure: 300
    secondsAfterSuccess: 300
  serviceAccountName: workflow
  entrypoint: main
  templates:
    - name: main
      plugin:
        argocd:
          # `actions` is a nested list. Items of inner arrays run in parallel. Top-level arrays run in sequence.
          # In this example, each inner array has only one item. The syncs run in sequence.
          actions:
            # TODO: support other action types, e.g. `cluster` and `repository`.
            - - app:
                  sync:
                    apps:
                      - name: guestbook
                    options:
                      - ServerSideApply=true
                timeout: 10s
            # Uncomment this to test a failed sync.
#            - - app:
#                  sync:
#                    apps:
#                      - name: not-real
