kind: ExecutorPlugin
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd
  annotations:
    workflows.argoproj.io/description: |
      This is an ArgoCD plugin that allows you to interact with an argocd instance of your choice

      Example:

      ```yaml
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        generateName: argocd-example-
      spec:
        entrypoint: main
        templates:
          - name: main
            plugin:
              argocd:
                serverUrl: https://my-argocd-instance.com/
                actions:
                  - sync:
                      project: default
                      app: guestbook
                  - refresh:
                      project: default
                      app: guestbook
      ```
    workflows.argoproj.io/version: '>= v3.3'
spec:
  sidecar:
    container:
      name: argocd-executor-plugin
      image: python:alpine
      command: [ python, -uc ]
      ports:
        - containerPort: 4355
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
