name: Build image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'crenshaw-dev/argocd-executor-plugin'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: crenshawdotdev
          password: ${{ secrets.DOCKERHUB_PASSWORD || inputs.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: crenshawdotdev/argocd-executor-plugin:${{ inputs.tag || 'latest' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.13.0'
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_call' }}
      - name: Sign ${{ inputs.tag }} image
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY crenshawdotdev/argocd-executor-plugin:${{ inputs.tag }}
          # Displays the public key to share.
          cosign public-key --key env://COSIGN_PRIVATE_KEY
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_call' }}
